### ISSUE TITLE
Could not submit form.

### ISSUE THREAD

**Issue by snj07** [abner/flutter_js#1]
I am trying to submit a form as given in [this](https://stackoverflow.com/a/3259946/4788260) example. But it's not working. I want to open different URL after submission of form. Could you please tell me if it should work?

**Comment by abner** [comment]
no. it should not work. this package does not run javascript in a webview.
it uses a small javascript engine called quickjs and only has the purpose to allow the flutter application to get javascript dinamically from server and evaluate it inside the application.

I recommend you try the package https://pub.dev/packages/flutter_view or https://pub.dev/packages/interactive_webview if you want html + javascript + css inside your flutter app. Regards

**Comment by snj07** [comment]
These plugin are not solving my use case. I have one API that returns html form with hidden input fields (the input field values are fetched from some other APIs), post method and submit button. I want to show that form button on a card of a list(can be web view) and when user clicks on submit button it should open another webpage in full screen. Could you please suggest something here? I am stuck from a long time. Thanks in advance.
