### ISSUE TITLE
Call a function with parameters

### ISSUE THREAD

**Issue by ARASHz4** [abner/flutter_js#109]
How to call a function with parameters from dart to js?

**Comment by PanneerDev** [comment]
**add.js**
function add(a, b) {
    return  a + b;
}


**dart**

final JavascriptRuntime runtime= getJavascriptRuntime();
int a =10;
int b=20;

String addJS = await rootBundle.loadString("assets/add.js");
final add = runtime.evaluate("""$addJS\n add($a,$b);""");
debugPrint("add= ${add.stringResult}");
