### ISSUE TITLE
Using npm packages like CKEditor

### ISSUE THREAD

**Issue by mustafa-fahimi** [abner/flutter_js#141]
Is it possible to use npm packages like CKEditor or Editor.js with Flutter_js or it's just for loading single js files?

**Comment by zhouxiaofu** [comment]
Take he dependency as an example:

`npm install he`

Create a js template file, such as template.js

```js
import he from 'he';

window.myModule = { he } // To prevent he from being renamed by rollup
```

Create rollup.config.js in the root directory, specify to package template.js, put the packaged js file in the flutter project, create JavascriptRuntime, read the code of the file first, and then execute it. Now you can use he

**Comment by abneroliveira-toast** [comment]
can load javascript files from bundling but those should be javascript libraries that aren't DOM based.
If your javascript code needs to render something (any visual component or anything which relies on browsers API), you should use a WebView.

**Comment by abner** [comment]
can load javascript files from bundling but those should be javascript libraries that aren't DOM based.
If your javascript code needs to render something (any visual component or anything which relies on browsers API), you should use a WebView.
