### ISSUE TITLE
add plugin Linux macos windows support

### ISSUE THREAD

**Issue by mabDc** [abner/flutter_js#16]
Hi, flutter_js is awsome. I used this plugin in my app, thanks for your work.

I'm Interested in using js not only mobile platforms but desktop platforms. Becase of quickjs writting by c language, I had edited some code from [history_commit](https://github.com/abner/flutter_js/tree/de9a82b1382206a0df8ed9f4cac9f6e5a9eb3dc7) five months ago, and it finally works well in Linux, macos, and windows (code in [flutter_js](https://github.com/mabDc/eso/tree/master/modules/flutter_js)).

 I also tried flutter_jscore, and had submited a [pull_request](https://github.com/xuelongqy/flutter_jscore/pull/5) to support windows in Aug, but ffi in dart is incomplete and I found it not perfect to me.

So, I think you may add desktop platforms support if you are planning to.

In addition, I recommend another flutter quickjs plugin [flutter_qjs](https://pub.dev/packages/flutter_qjs), it has better interaction with dart, more similar to [flutter_liquidcore](https://pub.dev/packages/flutter_liquidcore), but uses quickjs too. You may have a look at it.

**Comment by abner** [comment]
Thanks!

Ok, i will evaluate this idea of add support to another platforms. I saw the flutter_qjs plugin too (nice piece of code to integrate to quickjs also).

Now i'm of a stage of implement some other plugins with uses flutter_js to bring some nice facilities to Flutter applications, so new platforms supports would take some time to be added. 

But i'm open for contributtions.
