### ISSUE TITLE
I hava got [object Object].

### ISSUE THREAD

**Issue by AndsteLyc** [abner/flutter_js#17]
Hi, I need help.👋
I have this code:
```
String codeStr = '(function(){return [{a:"b"}]}())';
JsEvalResult jsEvalResult = getJavascriptRuntime().evaluate(codeStr);
print(jsEvalResult.stringResult);
```

output:
```
flutter: SET TIMEOUT EVAL RESULT: 1
flutter: [object Object]
```

If i use:```print(jsEvalResult.rawResult);```
output:
```
flutter: SET TIMEOUT EVAL RESULT: 1
flutter: Pointer<NativeType>: address=0x129294150
```

How do I get the results I'm striving for?
```
[{a:"b"}]
```

**Comment by AndsteLyc** [comment]
Tks, I got the result I wanted by going```onMessage```

**Comment by Jethro87** [comment]
@AndsteLyc How did you manage to do this, exactly? I'm getting the same `[object Object]` result that you were. Thanks.
