### ISSUE TITLE
then How should this asynchronous JS be called?

### ISSUE THREAD

**Issue by sunbx** [abner/flutter_js#18]
var promise = client.getMap(config.map);
promise.then(function (rs) {
    console.log(rs);
});

**Comment by abner** [comment]
I couldn't understand. Would you please elaborate your question a little bit?

**Comment by sunbx** [comment]
I mean, if JS's method callback is asynchronous, how does the callback give the flutter?
For example, after I make a successful HTTP request through JS, the request is returned to the flutter

**Comment by sunbx** [comment]
?????????????

**Comment by winterdl** [comment]
Could we call dart async function from js

```
javascriptRuntime.onMessage('someChannelName', (dynamic args) async {
     await task1(args);
});
```

and then, in js we use promise to take the value from async call:

`sendMessage('someChannelName', JSON.stringify([1,2,3]).then((value) {.....});`
