### ISSUE TITLE
class not work!

### ISSUE THREAD

**Issue by mrtian** [abner/flutter_js#19]
class TestClassName{
   ...
}

var testClass= new TestClassName();

not work!

**Comment by abner** [comment]
class does work. But if this code were evaluated more than once, then the javascript will fail with an error pointing you are redeclaring a already declared class.

You should also have a last statement which returns something. In Javascript, variable assignments does not returns anything;

Your last call in this statement should be `testClass`:

```js
class TestClassName{
...
}

var testClass= new TestClassName();
JSON.stringify(testClass);
```
