### ISSUE TITLE
SyntaxError: unexpected end of string

### ISSUE THREAD

**Issue by cacard** [abner/flutter_js#20]
when evaluate this：

var __data__ = [{"id":10,"jsId":1,"areaCode":"","areaType":1,"areaName":"实验学校","parentId":0,"areaStatus":1,"11":1,"parkingCount":1,"freeParkCount":1,"areaPath":""}];

should be caused by '验', not support this character？

**Comment by abner** [comment]
working in the most recent version of flutter_js
