### ISSUE TITLE
Code Comments/Explanation

### ISSUE THREAD

**Issue by mlopez0** [abner/flutter_js#22]
Hi Abner,

On the example provided when you want to load a javascript you load the ajv.js library like this: 
 
```
String ajvJS = await rootBundle.loadString("assets/js/ajv.js");
widget.jsRuntime.evaluate("var window = global = globalThis;");
await widget.jsRuntime.evaluateAsync(ajvJS + "");


```
Could you explain those three lines of code?

I'm trying to load the [ssim.js](https://github.com/darosh/image-ssim-js) library which natively take less than 50 ms to provide a result. But using flutter_js it takes around 1500 ms. I'm trying to find out where is the bottle neck since I have to evaluate this function 300 times. 
The time passes from 9 seconds to around 5 minutes.

This is my code 

```
String ssimJS = await rootBundle.loadString("assets/SSIM/dist/image-ssim.min.js");
widget.jsRuntime.evaluate("var window = global = globalThis;");
await widget.jsRuntime.evaluateAsync(ssimJS + "");
JsEvalResult evalSsim = widget.jsRuntime.evaluate(""" ssim('image1','image2')"""");

```

**Comment by mlopez0** [comment]
I couldn't find the bottle neck, decided to take a different approach without using this repo

**Comment by rainerlonau** [comment]
Hi @mlopez0,
what approach did you come up with?
Thanks

**Comment by mlopez0** [comment]
> Hi @mlopez0,
> what approach did you come up with?
> Thanks


Hi @rainerlonau 

As you can see on my original message I was trying to load the ssim.js library. So I removed the middle man and translate the ssim JS code into Dart code.

**Comment by sukhcha-in** [comment]
> 

Amazing! How did you convert whole library into dart?
