### ISSUE TITLE
How do you import/use a Javascript file and run functions from it?

### ISSUE THREAD

**Issue by getgizmo** [abner/flutter_js#28]
Thank you for this plugin!  I am able to to execute Javscript code eg. "Math.abs(-2);" but my goal is to call functions from this 32,000 line Javascript file I have that has a bunch of functions in it. I tried something really crazy, which was making a raw string that has all of the Javascript code but it crashes my app with "FAILED BINDER TRANSACTION !!!" because im guessing im passing too much data via that dart lib I made that has the raw string.  What do you suggest I do?

**Comment by cacard** [comment]
quickjs is a IoT javascript engine, you'd better simpllize your js code as simple as possible.

**Comment by getgizmo** [comment]
> quickjs is a IoT javascript engine, you'd better simpllize your js code as simple as possible.

I will try that. Unfortunately this js lib was generated from Golang code via gopherjs
