### ISSUE TITLE
Execute JS code hosted somewhere else

### ISSUE THREAD

**Issue by vegidio** [abner/flutter_js#30]
Hi, first of all, thanks for building such an amazing package!

I have a question: is it possible to have my JS code hosted in a website and make this package load my code from there? My idea is to have some part of my app's business logic in a JS file and if I need to update this logic somehow then I would just need to upload a new JS to my website, without having to submit a new version of the app to production.

Thanks.

**Comment by abner** [comment]
Yes, you just need to setup the native configuration (AndroidManifest.xml in Android and entitlement files on IOS) to allow your app to communicate with external sources
