### ISSUE TITLE
Trying out flutter_js failed due to dependency issues

### ISSUE THREAD

**Issue by oakstair** [abner/flutter_js#31]
I wanted to try out some js in my project (that was recently upgraded to flutter 2) but I get this.

    /Users/gunnar/dev/flutter/bin/flutter --no-color pub get
    Running "flutter pub get" in chess-champion...                  

    Because chess_champion depends on flutter_js ^0.2.2+0 which depends on http ^0.12.2, http ^0.12.2 is required.
    So, because chess_champion depends on http ^0.13.0, version solving failed.
    pub get failed (1; So, because chess_champion depends on http ^0.13.0, version solving failed.)

Ok, so I tried to downgrade http but then I get

    /Users/gunnar/dev/flutter/bin/flutter --no-color pub get 
    Running "flutter pub get" in chess-champion...                  

    Because firebase 9.0.0 depends on http ^0.13.0 and no versions of firebase match >9.0.0 <10.0.0, firebase ^9.0.0 requires 
    http ^0.13.0.
    So, because chess_champion depends on both firebase ^9.0.0 and http ^0.12.2, version solving failed.
    pub get failed (1; So, because chess_champion depends on both firebase ^9.0.0 and http ^0.12.2, version solving failed.)

**Comment by abner** [comment]
hi. I will try to use range in the package dependencies to avoid this issue

**Comment by abner** [comment]
Released the version 0.2.3+0 which change http dependencies to a range, so it should work now
