### ISSUE TITLE
how do i pass a variable from dart to jscript ?

### ISSUE THREAD

**Issue by iulian0512** [abner/flutter_js#32]
if i have for example the following js to evaluate "y+2-1" and i want to pass y variable to the jsengine how would i do that ?

**Comment by abner** [comment]
you have some alternatives:

1. You can evaluate a expression which defines a javascript variable and after it you can reference this variable in subsequent expressions.

```
flutterJS.evaluate('var dataObjectFromDart = { "y":  $someDartVariable }; ');
final jResult = flutterJS.evaluate('var result = dataObjectFromDart.y + 2 - 1;');
```

2. You can define a javascript function e compose a expression which compose the expression calling this function and passing the value to the function.

```
flutterJS.evaluate('function doSomething(variableX) { return variableX + 1; }");
final jResult = flutterJS.evaluate('doSomething(${numericDartVariable});');
```

**Comment by sumitbhanushali** [comment]
@abner i am getting 
```
I/flutter (11559): SyntaxError: expecting '}'
I/flutter (11559):     at <eval>:1
```

when trying to use big dart object ~60 properties inside dart map
