### ISSUE TITLE
Webpack configuration for bundling libraries compatible with flutter_js

### ISSUE THREAD

**Issue by fbennets** [abner/flutter_js#38]
Hi @abner,
first and foremost, thank you for this awesome library!

I have currently have an issue  where I am trying to load our own JavaScript library which is bundled with webpack as an UMD library. I managed load a generic JavaScript file containing some test functions and executing them afterwards using the AJV example. Loading the bundled library in a browser using a "script"-tag in an HTML-file works fine, its available in the window/global namespace. However, when  I'm trying to load the library using flutter_js, it does not become available in the global namespace.

I saw you mentioning that you are using webpack to bundle libraries you load into flutter_js. Therefore, I wanted to ask if you could kindly share your webpack.config.js and how you are exporting you library to the global namespace? Afterwards I could do a PR to enhance to documentation on how to embed libraries, if you'd like me to.

This is the library I am trying to embed:
[index.js](https://github.com/open-decision/open-decision-js-interpreter/blob/modularise-lib-into-core/src/index.js)
 
The export in the library is done this way:
```javascript
class Render {
...}
module.exports = Render;
```

I also tried `export default class {...}` which also worked fine in a browser but not in flutter_js.

This is the [webpack.config.js](https://github.com/open-decision/open-decision-js-interpreter/blob/modularise-lib-into-core/webpack.config.js):

```javascript
module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'open-decision-js-core.js',
    library: {
        name: 'OpenDecisionJSCore',
        type: 'umd',
      },
  },
};
```

The loading of the library in flutter follows your example:
```dart
String libJS =
            await rootBundle.loadString("assets/js/open-decision-js-core.js");

        this.jsRuntime.evaluate("""var window = global = globalThis;""");

        this.jsRuntime.evaluate("$libJS");
```
However, in the following calls, `global.OpenDecisionJSCore` is undefined.

I'd really appreciate some guidance!

**Comment by fbennets** [comment]
I solved the issue, the eval of the library failed, as I used some syntax which WebKit on MacOS didn't support yet. Took me some time to figure out that I'll only see syntax errors when wrapping the line `this.jsRuntime.evaluate("$libJS");` in a print statement.
I'll see if manage to write some guidance on importing libraries using flutter_js in the next weeks!

**Comment by suraj740** [comment]
@fbennets i am also using some custom library bundled with webpack but i am getting error `Can't find variable: document`

**Comment by fbennets** [comment]
Well that's not an Webpack issue. In a browser environment `document` contains the wepage's DOM tree [(see here](https://developer.mozilla.org/en-US/docs/Web/API/Document)). So you're library is trying to access the DOM which is not present, as you're not executing JS within a website. What are you trying to do? If you're trying to render elements using JS, you're probably better of with using a webview plugin in Flutter (like [flutter_webview_plugin](https://pub.dev/packages/flutter_webview_plugin) or [webview_flutter ](https://pub.dev/packages/webview_flutter). They should allow you to execute Javascript to render elements or manipulate the DOM.

**Comment by suraj740** [comment]
@fbennets I want to load js bundle in my flutter app ```
String lfMap =
                await rootBundle.loadString("assets/library/index_bundle.js");

            print(lfMap);
            javascriptRuntime
                .evaluate("""var window = global = self = globalThis;""");

            var test = javascriptRuntime.evaluate(lfMap);
```

**Comment by stonesong** [comment]
found a solution using:
`
 libraryTarget: 'var',
    globalObject: 'this',
`

in my webpack config
