### ISSUE TITLE
Its possible to call DartCode from JavaScript

### ISSUE THREAD

**Issue by EduFrazao** [abner/flutter_js#39]
Hi. Its possible to call flutter code in anyway, from inside JavaScript code? Like for example, like Java JSR 223 or another any other method?

**Comment by fbennets** [comment]
Did you try this, it's mentioned in the documentation?

> How to call dart from Javascript
> 
> You can add a channel on JavascriptRuntime objects to receive calls from the Javascript engine:
> 
> In the dart side:
> ```dart
> javascriptRuntime.onMessage('someChannelName', (dynamic args) {
>      print(args);
> });
> ```
> Now, if your javascript code calls sendMessage('someChannelName', JSON.stringify([1,2,3]); the above dart function provided as the second argument will be called with a List containing 1, 2, 3 as it elements.
