### ISSUE TITLE
errors in building for windows desttop

### ISSUE THREAD

**Issue by Tanthus** [abner/flutter_js#41]
After getting errors while trying to add package to my app, I tried to build the example.   Got these errors, the same as in my app:

    ../lib/javascriptcore/binding/js_object_ref.dart(318,14): error GD65BB2B6: The getter 'addressOf' isn't defined for the class 'JSStaticValue'. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    ../lib/javascriptcore/binding/js_object_ref.dart(394,14): error GD65BB2B6: The getter 'addressOf' isn't defined for the class 'JSStaticFunction'. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    ../lib/javascriptcore/jscore/js_class.dart(16,70): error GD65BB2B6: The getter 'addressOf' isn't defined for the class 'JSClassDefinition'. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    ../lib/javascriptcore/jscore/js_object.dart(454,18): error GD65BB2B6: The getter 'addressOf' isn't defined for the class 'JSStaticFunction'. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    ../lib/quickjs/qjs_typedefs.dart(4,7): error G09587AA0: Struct 'JSContext' is empty. Empty structs are undefined behavior. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    ../lib/quickjs/qjs_typedefs.dart(6,7): error G09587AA0: Struct 'JSRuntime' is empty. Empty structs are undefined behavior. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    ../lib/quickjs/qjs_typedefs.dart(8,7): error G09587AA0: Struct 'JSValueConst' is empty. Empty structs are undefined behavior. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(238,5): error MSB8066: Custom build for 'C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\CMakeFiles\94d6287bc813f77cde70b7ad0db8efa7\flutter_windows.dll.rule;C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\CMakeFiles\25f25885ad462a9188635d74cda2893b\flutter_assemble.rule' exited with code 1. [C:\proj\prolific-app-flutter\test\flutter_js\example\build\windows\flutter\flutter_assemble.vcxproj]
    Exception: Build process failed.

The output of flutter doctor

    Doctor summary (to see all details, run flutter doctor -v):
    [√] Flutter (Channel beta, 2.2.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    [√] Chrome - develop for the web
    [√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.5)
    [√] Android Studio (version 4.1.0)
    [√] VS Code (version 1.56.0)
    [√] Connected device (3 available)
    
    • No issues found!

Couldn't find any extra setup for windows in the help

**Comment by abner** [comment]
fixed on flutter_js 0.5.0+0
