### ISSUE TITLE
How to use with `readability.js`

### ISSUE THREAD

**Issue by tuanbs** [abner/flutter_js#44]
Hello, can you please tell if it's possible to use this plugin with `readability.js`?

**Comment by abner** [comment]
I don't think so. flutter_js just brings a javascript engine to Flutter. `readabilty.js` parses the DOM and DOM isn't present in the Javascript Engines used by flutter_js. You would load some simulated DOM, like JSDOM, but i have no idea if `readability.js` will work with jsdom.
