### ISSUE TITLE
Latest version of flutter_js 0.5.0+0 is not working

### ISSUE THREAD

**Issue by ashemetov** [abner/flutter_js#48]
I am using flutter_js 0.5.0+0 and Flutter 2.2.2, everything is working fine under simulator but fails on physical device (tested on two different Android phones). Something wrong with returned values - app is stuck when, let's say, jsonDecode applied onto jsResult.stringResult.
Even demo app flutter_js_example supplied with a package has the same behavior, works under simulator, fails on real device.

Previous combination (flutter_js 0.4.0+6 and Flutter 2.0.5) worked without issues.

**Comment by ashemetov** [comment]
Update: latest version sets stack size to 0, as result loaded library is not kept in the memory, so evaluation fails. I worked around it by explicitly setting stack size:

getJavascriptRuntime(extraArgs: {'stackSize': 1024 * 1024});

**Comment by abner** [comment]
> Update: latest version sets stack size to 0, as result loaded library is not kept in the memory, so evaluation fails. I worked around it by explicitly setting stack size:
> 
> getJavascriptRuntime(extraArgs: {'stackSize': 1024 * 1024});

Thanks, i will apply the stackSize to the runtime initialization

**Comment by abner** [comment]
fixed on version 0.5.0+2
