### ISSUE TITLE
Example of calling a method

### ISSUE THREAD

**Issue by tryflowk** [abner/flutter_js#5]
Hello, first of all thanks for your effort!

I need to use the rrule.js library but I couldn't find out how I can call a method from it. Could you please provide an example?

Thanks again.

@fjumes
Florianópolis - BR

**Comment by abner** [comment]
Hi @fjumes. I just added examples of integration with Ajv.js https://github.com/abner/flutter_js/blob/master/example/lib/ajv_example.dart

Please, let me know if it is enough.

@abner 
Salvador - BA

**Comment by abner** [comment]
i didn't know rrule.js. But for what i found it handles ICalendar date recurrence.

Did you tried this library https://pub.dev/packages/ical_serializer?

**Comment by abner** [comment]
closed for inactivity
