### ISSUE TITLE
axios XHR error

### ISSUE THREAD

**Issue by xiqishow** [abner/flutter_js#51]
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
I use axios.js to Send GET request,but get error :
`ERROR: Unexpected token ':'. Expected ';' after variable declaration.
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Bad state: No element
#0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
#1      JavascriptRuntimeXhrExtension.enableXhr.<anonymous closure>.<anonymous closure>
package:flutter_js/extensions/xhr.dart:273
#2      JavascriptRuntimeXhrExtension.enableXhr.<anonymous closure>.<anonymous closure>
package:flutter_js/extensions/xhr.dart:271
#3      List.forEach (dart:core-patch/growable_array.dart:403:8)
#4      JavascriptRuntimeXhrExtension.enableXhr.<anonymous closure>
package:flutter_js/extensions/xhr.dart:271
#5      _rootRunUnary (dart:async/zone.dart:1362:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
#8      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1207:26)
#9      _rootRunUnary (dart:async/zone.dart:1370:13)
#10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#11     _CustomZone.bindUnaryCallb<…>`
I debug the code, found 274 line in file dart,the "pendingCall.method" is upper for example "GET", but the HttpMethod.values list is lower for example "get",
so I change the code to this it workd
` HttpMethod eMethod = HttpMethod.values.firstWhere(
            (e) => e.toString() == ("HttpMethod.${pendingCall.method?.toLowerCase()}"));`

please fix this in offical version, thank you.

**Comment by abner** [comment]
Already fixed in flutter_js version 0.5.0+6
