### ISSUE TITLE
Support isolate

### ISSUE THREAD

**Issue by 623637646** [abner/flutter_js#52]
My JS code is enormous computation. I have to call it on non-main isolate. But I can't do it cause of a crash: "Unhandled Exception: Exception: Null check operator used on a null value". The reason is spawned isolates do not have access to the root bundle  https://github.com/flutter/flutter/issues/61480#issuecomment-673985944

This demo shows what I want. 
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_js/flutter_js.dart';

void main() async {
  runApp(MaterialApp(
    home: Scaffold(
      body: Center(child: Text("hello word")),
    ),
  ));

  final jsCode = "2+3;";

  // This code has error: "Unhandled Exception: Exception: Null check operator used on a null value".
  final String result = await compute(_execute, jsCode);

  // This code works fine.
  // final int result = await _execute(jsCode);
  print(result);
}

Future<T> _execute<T>(String jsCode) async {
  final javascriptRuntime = getJavascriptRuntime();
  final result = javascriptRuntime.evaluate(jsCode);
  return javascriptRuntime.convertValue(result);
}
```

**Comment by wardy484** [comment]
This would be great, I have a process that does a lot of processing (unfortuantely in JS).

**Comment by jpolstre** [comment]
I had some problems with this package and on reviewing the code I found that it depends on Quickjs Dart, which apparently already performs the operations in a separate isolation.

**Comment by sirenoremac** [comment]
If you do not need xhr, you can pass false to the xhr parameter of getJavascriptRuntime() and it will not try to access the root bundle:
final javascriptRuntime = getJavascriptRuntime(xhr: false);

If you do this, it will work in an isolate.
