### ISSUE TITLE
How to install/use Base64-js package in flutter_js

### ISSUE THREAD

**Issue by sourabhshastri1990** [abner/flutter_js#58]
Hi,

Thanks for providing a convenient way to execute JavaScript Code in Flutter.

I would like to ask how to install/use a JS package to use it in flutter_js javascriptRuntime.evaluate()?

Thanks and Regards,
Sourabh Shastri

**Comment by abner** [comment]
npm packages would be used if them were bundled to a file using webpack or esbuild. After you can evaluate their codes through jsRuntime.evaluate. Packages supported should not rely in browser API, with some few exceptions (flutter_js adds setTimeout, console.log, xhr, fetch to the javascript engine, so if your javascript package rely on these, it would work).
