### ISSUE TITLE
unable to use BigInt with flutter_js

### ISSUE THREAD

**Issue by toseefkhan403** [abner/flutter_js#61]
Error:
`I/flutter ( 8408): ReferenceError: 'BigInt' is not defined
I/flutter ( 8408):     at intToBigInt (<eval>:2)
I/flutter ( 8408):     at <eval> (<eval>:4)
I/flutter ( 8408): ReferenceError: 'BigInt' is not defined
I/flutter ( 8408):     at intToBigInt (<eval>:2)
I/flutter ( 8408):     at <eval> (<eval>:4)`

Code to reproduce the error:
`JsEvalResult result = await flutterJs.evaluate("""
      function intToBigInt(num) {
        return BigInt(num);
      } 
      intToBigInt(9223372036854775807);
      """);
      print(result.stringResult);`

Testing this on Android. Have tried using both QuickJS and JavascriptCore.
This seems like a version issue. Are there any fixes available?

**Comment by abner** [comment]
BigInt is not supported in JavascriptCore and QuickJS. So you need to provide a polyfill, which would use Dart Int64 as the underneath implementation.

**Comment by mkassan** [comment]
Recently, I've tried the BigInt with flutter_js, it seems that it does not work even if QuickJS doc says that they support it today : https://bellard.org/quickjs/

Any note about this topic?
