### ISSUE TITLE
does promise and async function really work on Android platform with quickjs

### ISSUE THREAD

**Issue by taoyiran2008** [abner/flutter_js#64]
neither flutter_js nor flutter_qjs support promise, resolve('xxx') just sink to the sea

**Comment by Hamza5** [comment]
Yes, it does, check answers of the closed issue #25 . But it may be better to switch to the JavaScriptCore engine.

Also, to convert a returned JS `Promise` into a Dart `Future`, the easiest way is to call `javascriptRuntime.handlePromise`. It will do all the required work without struggling with the `sendMessage` and `onMessage` stuff.
