### ISSUE TITLE
If javascript package code  depends on other modules ，code has require statement.What shoud i do?

### ISSUE THREAD

**Issue by hjue** [abner/flutter_js#77]
I use [turndown](https://github.com/mixmark-io/turndown),it's a html to markdown convert.It depends on [domino](https://github.com/fgnass/domino).

What shoud i do ?

The flutter_js can support the implementation of `require('assets://xxxx.js') `?

**Comment by IanWambai** [comment]
Also, is it possible to import and use Javascript packages with this library?

**Comment by dmdeklerk** [comment]
You should use something like https://esbuild.github.io/ or webpack and build and have that package all your code into in a single file. 
Then from Flutter code read that file and execute it through flutter_js eval.

**Comment by abner** [comment]
Yeah @hjue and @IanWambai , you definetely should use some bundler (webpack, esbuild) to generate the js file bundle which you will load using flutter_js eval.



> You should use something like https://esbuild.github.io/ or webpack and build and have that package all your code into in a single file. Then from Flutter code read that file and execute it through flutter_js eval.
