### ISSUE TITLE
setTimeout/setInterval is not execute correctly  in android.

### ISSUE THREAD

**Issue by mrtian** [abner/flutter_js#9]
time is 0; 
![image](https://user-images.githubusercontent.com/363241/86103919-f6df4980-baef-11ea-90c3-1ff3d9bf8c53.png)
var a = new Date().getTime();
        setTimeout(function(){
            Jfui.log("timeout:"+(new Date().getTime()-a));
        },5000);

**Comment by abner** [comment]
setTimeout, setInterval were not supported by the underlying javascript engines (quickjs on Android and JavascriptCore on IOS).
There is a alternative to use Kotlin code on Android and Swift Code on IOS to provide surrogate implementations. But is not implemented just yet.
