### ISSUE TITLE
Incompatibility issue

### ISSUE THREAD

**Issue by ashemetov** [abner/flutter_js#93]
Recently number of packages were promoted to newer versions, so I started getting errors like:
"Because flutter_js 0.5.0+6 depends on ffi ^1.0.0 and device_info_plus_windows >=3.0.1 depends on ffi ^2.0.1, flutter_js 0.5.0+6 is incompatible with device_info_plus_windows >=3.0.1."
Can you please update dependencies with ffi v2?

**Comment by alexaung** [comment]
Yes, because of this, we can't upgrade other plugin. Are they still supporting this plugin?
