### ISSUE TITLE
depends on ffi is too old

### ISSUE THREAD

**Issue by yangyxd** [abner/flutter_js#94]
Thank you for providing this widget!

Because open_filex >=4.0.0 depends on ffi ^2.0.1 and flutter_js 0.5.0+6 depends on ffi ^1.0.0, open_filex >=4.0.0 is incompatible with flutter_js 0.5.0+6.
And because no versions of flutter_js match >0.5.0+6 <0.6.0, open_filex >=4.0.0 is incompatible with flutter_js ^0.5.0+6.
So, because eso depends on both flutter_js ^0.5.0+6 and open_filex ^4.1.1, version solving failed.
pub get failed (1; So, because eso depends on both flutter_js ^0.5.0+6 and open_filex ^4.1.1, version solving failed.)

**Comment by kristjanbauhub** [comment]
🙏
